@startuml
left to right direction
skinparam packageStyle rectangle

' Définition des acteurs
actor "Professionnel Santé" as Pro
actor "Administrateur" as Admin
actor "Utilisateur" as User

' Héritage des acteurs (Les flèches qui contournent le cadre)
User <|-- Pro
User <|-- Admin

rectangle "System d'information médical" {

    ' Cas d'utilisation pour le Professionnel de Santé
    usecase "Programmer et suivre\nconsultation de(s) patient(s)" as UC_Programmer
    usecase "Creer Consulter et Mettre ajout\ndossier medical" as UC_Dossier
    usecase "Verifier disponibiliter" as UC_Dispo

    ' Cas d'utilisation pour l'Administrateur
    usecase "Gérer les comptes utilisateurs\n(Créer et Supprimer)" as UC_GererCompte
    usecase "Gerer les droits d'acces" as UC_Droits
    usecase "Consulter statistiques" as UC_Stats
    usecase "Catégoriser les consultations et \n dossiers patients par spécialité \n médicale " as UC_Categorisation
    usecase "Importater/exporter les données \n au format .csv" as UC_ImportExport 
    


    

    ' Cas d'utilisation commun (Authentification)
    usecase "S'authentifier" as UC_Auth

    ' Relations Acteurs -> Cas d'utilisation
    Pro -- UC_Programmer
    Pro -- UC_Dossier

    Admin -- UC_GererCompte
    Admin -- UC_Droits
    Admin -- UC_Stats
    Admin-- UC_Categorisation
    Admin -- UC_ImportExport
    

    ' Relation directe de l'Utilisateur (selon le diagramme)
    User -- UC_Auth

    ' Relations <<include>> vers S'authentifier
    UC_Programmer ..> UC_Auth : <<include>>
    UC_Dossier ..> UC_Auth : <<include>>
    UC_GererCompte ..> UC_Auth : <<include>>
    UC_Droits ..> UC_Auth : <<include>>
    UC_Stats ..> UC_Auth : <<include>>
    UC_Categorisation ..> UC_Auth : <<include>>
    UC_ImportExport ..> UC_Auth : <<include>>
    

    ' Autre relation <<include>> spécifique
    UC_Programmer ..> UC_Dispo : <<include>>
}
@enduml
